apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-predictivo
  namespace: student-TU_USUARIO
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-predictivo
  template:
    metadata:
      labels:
        app: worker-predictivo
    spec:
      containers:
        - name: worker-predictivo
          image: TU_USUARIO_DOCKERHUB/worker-predictivo:latest
          envFrom:
            - configMapRef:
                name: app-config
