#ACL basico (controla qué tópicos puede usar cada usuario)
#Si un usuario autenticado no tiene ningún bloque abajo que lo mencione, no tiene acceso a ningun tópico (Hay que darle acceso explícito)
#Ejemplo Prueba
user usuarioPrueba
topic readwrite sensor/#
