# ============================================================
# ACL - Control de acceso a tópicos MQTT
# ============================================================

# ESP32: solo puede PUBLICAR en sensor/raw
user esp32
topic write sensor/raw

# Ingesta: solo puede LEER de sensor/raw
user ingesta
topic read sensor/raw

# Admin: acceso total (para pruebas)
user admin
topic readwrite #