apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-haccp
  namespace: student-aamonsalve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-haccp
  template:
    metadata:
      labels:
        app: worker-haccp
    spec:
      containers:
      - name: worker-haccp
        image: aamonsalve/cryometric-worker-haccp:latest
        envFrom:
        - configMapRef:
            name: app-config